[FEAT-21] add multi docs and versioning
taecontrol/moonguard-docs pull request #22
Opened 2023-07-18 19:34 UTC by AlexisTAE

close #21 

creo que hay que crear una rama develop para que no entre a main

2023-07-18 19:48 UTC, rpereira-tae commented
@AlexisTAE Crea la rama develop

2023-07-18 20:00 UTC, AlexisTAE commented
@rpereira-tae listo

2023-07-19 17:30 UTC, rpereira-tae commented
Me encontré un bug, cuando voy a la vista de Larvis se marca MoonGuard y Larvis en el navbar.

![image](https://github.com/taecontrol/moonguard-docs/assets/61505019/90deeb0a-1d6b-4edb-9b51-30a1b0ddbc69)

2023-07-19 17:39 UTC, rpereira-tae commented
Por alguna razón si das click en la versión te manda a la vista home, debería ser posible retirar ese comportamiento ya sea mediante el componente o desde la configuración de docusaurus:

https://github.com/taecontrol/moonguard-docs/assets/61505019/570329b2-1a86-49b9-86a1-1c0767f61053

2023-07-19 17:46 UTC, rpereira-tae requested changes

2023-07-19 17:46 UTC, rpereira-tae commented on docusaurus.config.js
> +            docsPluginId: "krater"
Podría ser que estos `docId` deban ser únicos?

2023-07-19 20:09 UTC, AlexisTAE commented
@rpereira-tae a donde deberia ir cuando se le da el boton de version?

2023-07-20 12:33 UTC, rpereira-tae commented
@AlexisTAE Deberíamos averiguar si se puede desactivar el hipervínculo o definir una ruta fija a la cual siempre redireccione

2023-08-10 13:15 UTC, rpereira-tae commented
We decided to not use the multi-doc feature from docusaurus because MoonGuard, Larvis and Krater will have their own documentation space.

2023-08-10 13:15 UTC, closed without merging