Feat-28 add MoonGuard 1.1.0 release
taecontrol/moonguard-docs pull request #29
Opened 2023-11-16 20:26 UTC by AlexisTAE

close #28

2023-11-17 00:51 UTC, rpereira-tae requested changes

2023-11-17 00:51 UTC, rpereira-tae commented on docs/installation.md
> +    '* * * * *' //<-- optional
Indicar a que parámetro se refieren

```suggestion
    '* * * * *', //<-- XXX XXX Cron
    '* * * * *' //<-- Delete Exceptions Cron
```

2023-11-20 15:14 UTC, rpereira-tae requested changes

2023-11-20 15:14 UTC, rpereira-tae commented on docs/installation.md
> +    '* * * * *', //<-- XXX XXX Cron
Por favor menciona a que comando pertenecen los crons, el XXX XXX era referencial.

2023-11-20 16:58 UTC, AlexisTAE commented on docs/installation.md
> +    '* * * * *', //<-- XXX XXX Cron
oka

2023-11-20 17:02 UTC, rpereira-tae approved these changes

2023-11-20 17:02 UTC, merged